          livenessProbe:
            httpGet:
              path: /auth
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /auth
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            periodSeconds: 15